### ISSUE TITLE
Some suggestions for WASM EVETNT

### ISSUE THREAD

**Issue by GavinXu520** [PlatONnetwork/PlatON-Go#1165]
The wasm event does not support the input parameter of Address type, and the input parameter of EVENT is not very reasonable. It is recommended to move closer to EVM but also have its own form of participation.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

**Comment by jatel** [comment]
Currently platon does not support anonymous events, and anonymous is false in the generated abi file.

In order to prevent the event topic data from being too long, the topics list field in the receipt will be a byte array represented by the big end if it is a numeric type, while the other types such as string, struct, vector, map will be a 32-byte byte array after the data is encoded by RLP.

**Comment by jatel** [comment]
The latest version of CDT has been processed, please download the latest CDT.
