### ISSUE TITLE
the gas used is different when invoke migrate contract using same parameters

### ISSUE THREAD

**Issue by fksyuan** [PlatONnetwork/PlatON-Go#1243]
1. the migrate gas used is 1125336 ，when transaction gaslimit 3094086。
2. the migrate gas used is 1109711，when transaction gaslimit 2094086。
2. the migrate gas used is 1094086，when transaction gaslimit 1094086。

**Comment by GavinXu520** [comment]
Yes, this is indeed a problem. The reason why the gasUse calculated by inputting different gas is different is because there is a calculation formula at the bottom. gas, but the problem is that the remaining value is directly assigned back, resulting in inconsistent gasUse each time.We will make changes in the next version

**Comment by fksyuan** [comment]
already fixed
