### ISSUE TITLE
migrate and transfer in WASM contracts, which remain in the pool when the balance is insufficient

### ISSUE THREAD

**Issue by qcxiao** [PlatONnetwork/PlatON-Go#1424]
Hi there,

migrate and transfer in WASM contracts, which remain in the pool when the balance is insufficient
——————————————————————————————
WASM合约migrate的过程中是可以对其转账的，但是当转账金额大于余额时，这个交易会一直在交易池里，如果保持gasPrice不变继续发交易后面的交易会一直出现nonce重复异常
#### System information

PlatON version: `0.13.0`
OS & Version: Windows/Linux/OSX
Commit hash : develop

**Comment by benbaley** [comment]
fixed in #1428 #1430

**Comment by GavinXu520** [comment]
Because the `platon::migrate` function is called in the contract code to perform the contract transfer and the balance transfer action at the same time, this information is in `tx.Data`, and in the implementation of the underlying `MigrateContract` external function, the account is found If the balance is insufficient and panic(ErrInsufficient) is thrown, the worker will eventually not pack the tx, but delete the tx with insufficient balance err in txpool, that is, tx with `ErrInsufficient` is judged according to `tx.Value`. Therefore, the information in `tx.Data` cannot be perceived, which eventually causes the tx to be always packaged by the worker and finally stays in the txpool。
