### ISSUE TITLE
Node cannot synchronize properly

### ISSUE THREAD

**Issue by mayong82** [PlatONnetwork/PlatON-Go#2191]
Node cannot synchronize properly

The error message is as follows:

ERROR [11-13 | 00:42:14.503] Read peer message error id=8e68362033bde1a8 conn=dynamic err=EOF

ERROR [11-13 | 00:42:14.504] CBFT message handling failed id=8e68362033bde1a8 conn=dynamic err=EOF

Node startup script command:

platon --identity platon --datadir /data/platon-nodedata --port 16789 --http.port 8545 --http.api platon,net,web3,personal --http --nodekey /data/platon-nodedata/nodekey --cbft.blskey /data/platon-nodedata/blskey --verbosity 1 --http.addr 0.0.0.0 --syncmode fast

**Comment by benbaley** [comment]
When you start a new node in fast mode, it will takes about 7-8 hours to wait for all the data synchronization to be completed due to your host hardware configuration and network resources, etc. What is the basis for your judgment that it cannot be synchronized properly? What is your platon‘s version?

**Comment by benbaley** [comment]
Closed due to prolonged non-response
