### ISSUE TITLE
Gas and platon. Call form query built - in contract will pollute snapshotDB data

### ISSUE THREAD

**Issue by niushicha1** [PlatONnetwork/PlatON-Go#472]
Estimated gas consumption of the platon.EstimateGas method and query class platon.Call method will lead to snapshotDB data pollution ~

**Comment by GavinXu520** [comment]
In the contract change data method (about non-query method) added checked the empty txHash, because of it is estimated that the platon.EstimateGas method of gas consumption and the platon.Call method about query methods are not transactions, these methods will be directly returns and the logic will not go down, there will be no dirty data polluting the data of the local node!
