### ISSUE TITLE
After Fast sync, the data appears inconsistent, resulting in panic after running for a while.

### ISSUE THREAD

**Issue by chenxiaodai** [PlatONnetwork/PlatON-Go#476]
Hi there,

    The initial 4 consensus nodes are running. One of the nodes is kicked out of the list because of being punished. Then, a new node and the original consensus node are proposed, and the synchronous synchronization is started from more than 90,000 blocks. To query the current real-time candidate list, the consensus node has not queried the node that has been punished, but the Fast synchronization node can still query.

After running to hundreds of thousands of blocks, when the checkout cycle is verified by the certifier, the data of the Fast sync node and the consensus node iterated from the snapshot DB are inconsistent, resulting in the node synchronization of the Fast synchronization.

#### System information

PlatON version: `feature/bump-version-to-0.7.2`
OS & Version: Linux
Commit hash : (if `develop`)
Serial number: #PLATON-430
#### Backtrace

````
[backtrace]
````

**Comment by cheng762** [comment]
The cause of this problem is

1.A, B two baselines, will write fixed data to the snapshot DB during initialization

2. B asynchronously deletes some of the above data during the run

3. A asynchronously synchronizes to B asynchronously. B asynchronously sends the existing snapshot data to the A interrupt. At this time, the A router contains the fixed data of 1 step and the data sent by B, and the deleted data of B has been deleted synchronously. , causing problems to occur

problem solved:

B synchronization clears the existing database when synchronizing the snapshot DB data quickly, and then synchronizes
